name: swis-api CI/CD pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: [ self-hosted, public, docker ]
    steps:
    - uses: actions/checkout@v2
    - name: Build new swapi image (with staging).
      run: make build

  dev_deploy:
    runs-on: [ self-hosted, public, docker ]
    needs: [ build ]
    steps:
    - uses: actions/checkout@v2
    - name: Run dev container and run end-to-end test on it.
      run: make devploy e2e

  dump_data:
    runs-on: [ self-hosted, public, docker ]
    needs: [ dev_deploy ]
    steps:
    - name: Dump production data.
      run: make dump
      env:
        APP_NAME: ${{ secrets.APP_URL }}

  prod_deploy:
    runs-on: [ self-hosted, public, docker ]
    needs: [ dump_data ]
    steps:
    - name: Deploy prod docker container, recreate container with fresh image.
      run: APP_ENVIRONMENT=production make run

  import_data:
    runs-on: [ self-hosted, public, docker ]
    needs: [ prod_deploy ]
    steps:
    - name: Import dumped data to production.
      run: make import_dump
      env:
        APP_NAME: ${{ secrets.APP_URL }}

